import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SmoothScroll from "@/components/SmoothScroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

import { getSettings } from "@/app/admin/settings/actions";

export const metadata: Metadata = {
  title: "RUMIO.ID",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data } = await getSettings([
    "contact_whatsapp", 
    "contact_email", 
    "general_office_address",
    "social_instagram",
    "social_facebook",
    "social_tiktok",
    "social_youtube",
    "general_site_description"
  ]);
  const waNumberRaw = data?.contact_whatsapp || "";
  // Pastikan format nomor yang bisa dipakai untuk link (hilangkan karakter non-angka)
  const waNumber = waNumberRaw.replace(/[^0-9]/g, "");

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col relative font-sans text-slate-900 bg-white">
        <SmoothScroll>
          <div className="flex flex-col min-h-screen">
            <Navbar whatsappNumber={waNumber} />
            <main className="flex-1">
              {children}
            </main>
            <Footer 
              whatsappNumber={waNumber} 
              rawWhatsapp={waNumberRaw}
              email={data?.contact_email}
              address={data?.general_office_address}
              socials={{
                instagram: data?.social_instagram,
                facebook: data?.social_facebook,
                tiktok: data?.social_tiktok,
                youtube: data?.social_youtube
              }}
              description={data?.general_site_description}
            />
          </div>
        </SmoothScroll>
      </body>
    </html>
  );
}
